modLoader="javafml"
loaderVersion="[32,)"
license="MIT License"
issueTrackerURL="https://github.com/Insane96/IguanaTweaksReborn/issues"
[[mods]]
modId="iguanatweaksreborn"
version="${file.jarVersion}"
displayName="IguanaTweaks Reborn"
displayURL="https://www.curseforge.com/minecraft/mc-mods/iguanatweaks-reborn"
credits="Thanks to Iguana for the original Mod"
authors="Insane96MCP"
description='''
Multiple changes to make Minecraft Harder.
Movement Restrictions, Farming, Mining, and much more.
'''
[[dependencies.iguanatweaksreborn]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iguanatweaksreborn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"